site_name: Raito
docs_dir: './source'

# Pages
use_directory_urls: false
nav:
  - Introduction: 'index.md'
  - Code documentation: '../rust/doc/raito/index.html'

# Setup
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - glightbox
  - search
